apps:
  - script: "gui-server.js"
    name: "infominer"
    cwd: "./src/server"
    args: "--DEV_MODE"
    instances: 1
    exec_mode: "fork"
    autorestart: true
    max_restart: 20
    watch: false